name: Deploy

on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment_name: ${{ inputs.target_environment }}
    secrets:
      deploy_token: ${{ secrets.DEPLOY_TOKEN }}